org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:+UseParallelGC
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.vfs.watch=true
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false
kotlin.incremental=false
kotlin.incremental.enabled=false
MAPBOX_DOWNLOADS_TOKEN=sk.placeholder

